version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependecies
          command: npm install
          working_directory: client

      - run:
          name: Unit testing
          command: npm run test:unit
          working_directory: client

workflows:
  welcome:
    jobs:
      - build
