version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:88:64:98:fe:db:c9:92:cc:b1:1d:bc:49:04:a6:9e"

      - checkout

      - restore_cache:
          keys:
            - circleci-demo-{{ checksum "client/package-lock.json" }}
            - circleci-demo

      - run:
          name: Install dependecies
          command: npm install
          working_directory: client

      - run:
          name: Unit testing
          command: npm run test:unit
          working_directory: client

      - run:
          name: Prepare releasing
          command: bash prepare-release.sh

      - run:
          name: Releasing
          command: bash release.sh

      - save_cache:
          paths:
            - client/node_modules
          key: circleci-demo-{{ checksum "client/package-lock.json" }}

workflows:
  welcome:
    jobs:
      - build
