version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - circleci-demo-{{ checksum "client/package-lock.json" }}
            - circleci-demo

      - run:
          name: Install dependecies
          command: npm install
          working_directory: client

      - run:
          name: Unit testing
          command: npm run test:unit
          working_directory: client

      - save_cache:
          paths:
            - client/node_modules
          key: circleci-demo-{{ checksum "client/package-lock.json" }}

workflows:
  welcome:
    jobs:
      - build
